# Generated by Django 5.1.3 on 2024-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
