# Generated by Django 5.1.3 on 2024-12-04 17:10

import accounts.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.UserManager()),
            ],
        ),
    ]
