# Generated by Django 5.1.3 on 2024-12-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_name'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
